- name: MARIADB RESTART
  systemd:
    name: sbm-agent
    state: restarted
    enabled: yes
- name: Restart httpd
  systemd:
    name: httpd
    state: restarted
    enabled: yes
  become: yes
  become_method: sudo