---
- name: R1soft Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Creates a repo
      copy:
        src: r1soft.repo
        dest: /etc/yum.repos.d/r1soft.repo