- name: Create Route53     
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - route53:
      state: present
      zone: 'huseyinakten.net'
      record: wp.huseyinakten.net
      type: A
      ttl: 7200
      value: 34.245.173.25