
- name: Install webserver
  hosts: worker1.huseyinakten.net
  become: true
  become_method: sudo
  connection: ssh
  tasks:
    - name: Install httpd
      package: 
        name: httpd
        state: present
    - name: Install PHP
      package:
        name: php
        state: latest
    - name: Create index.html file
      copy:
        content: Hello world
        dest:  /var/www/html/index.html
    - name: Start webserver
      systemd:
        name: httpd
        state: started
        enabled: yes


